Add some larger sizes to `View` -> `Window Size` (Fixes #3826)
TASEmulators/BizHawk pull request #3872
Opened 2024-03-17 02:31 UTC by SkiHatDuckie

Fixes #3826 

`View` -> `Window Size` can now be set to factors of x1-x10, instead of x1-x5 & x10.

Check if completed:
- [X] I have run any relevant test suites
- [X] I, the committer, have read the [licensing terms for contributors](https://github.com/TASEmulators/BizHawk/blob/master/contributing.md#copyrights-and-licensing) (last updated 2022-07-15) and am compliant

2024-03-17 08:29 UTC, YoshiRulz requested changes
If you're going to change this, please tear out the existing garbage and generate the 10 things in a loop. That will save you from needing to deal with the Designer as well.

2024-03-19 00:49 UTC, SkiHatDuckie commented
The code for generating the menu items + changing the zoom factor should be _significantly_ sexier now. As a bonus, if anyone for some reason requests factors beyond 10x, you can just increment the `max_factor` argument in MainForm.cs.<br>
 `WindowSizeSubMenu.DropDownItems.AddRange(CreateWindowSizeFactorSubmenus(max_factor: 10).ToArray());`

2024-03-19 10:24 UTC, YoshiRulz commented on src/BizHawk.Client.EmuHawk/MainForm.Designer.cs
> +			this.SelectSlot0MenuItem = new BizHawk.WinForms.Controls.ToolStripMenuItemEx();
Please revert unrelated changes.

2024-03-19 10:34 UTC, YoshiRulz requested changes

2024-03-19 10:34 UTC, YoshiRulz commented on src/BizHawk.Client.EmuHawk/MainForm.Events.cs
> +					Text = $"{i / 10}&{i % 10}x"
Clever. I'd like to keep "1x" rather than "01x" though. (There should be a `DivMod` somewhere too.)

2024-03-19 10:34 UTC, YoshiRulz commented on src/BizHawk.Client.EmuHawk/MainForm.Events.cs
> +				temp.Click += new System.EventHandler(this.WindowSize_Click);
```suggestion
				temp.Click += WindowSize_Click;
```

2024-03-19 10:34 UTC, YoshiRulz commented on src/BizHawk.Client.EmuHawk/MainForm.Events.cs
> +			foreach (ToolStripMenuItemEx item in WindowSizeSubMenu.DropDownItems)
This is a cast, right? So use the base class.

2024-03-19 10:34 UTC, YoshiRulz commented on src/BizHawk.Client.EmuHawk/MainForm.Events.cs
> +			}
```suggestion
			Config.TargetZoomFactors[Emulator.SystemId] = (int) ((Control) sender).Tag;
```

2024-03-19 10:34 UTC, YoshiRulz commented on src/BizHawk.Client.EmuHawk/MainForm.cs
> +			WindowSizeSubMenu.DropDownItems.AddRange(CreateWindowSizeFactorSubmenus(max_factor: 10).ToArray());
Why return a list if you're going to convert it to an array at the only call-site?

And there will only ever be one call-site, so you should inline it or use a local method.

2024-03-19 10:34 UTC, YoshiRulz commented on src/BizHawk.Client.EmuHawk/MainForm.cs
> +			if (Config.TargetZoomFactors[Emulator.SystemId] < (int) max_factor)
Ugly. Use a `const int` for the max.

2024-03-19 10:34 UTC, YoshiRulz commented on src/BizHawk.Client.EmuHawk/MainForm.cs
> +			if (Config.TargetZoomFactors[Emulator.SystemId] > (int) min_factor)
The minimum is always going to be 1x.

2024-03-19 20:15 UTC, YoshiRulz commented on src/BizHawk.Client.EmuHawk/MainForm.cs
> +			if (Config.TargetZoomFactors[Emulator.SystemId] < 10)
Not what I meant. (This is `const`, but more precisely it's a literal, and I was suggesting a field:)
```csharp
private const int WINDOW_SCALE_MAX = 10;
// ...
ToolStripItem[] CreateWindowSizeFactorSubmenus()
{
	ToolStripItem items = new[WINDOW_SCALE_MAX];
// ...
if (Config.TargetZoomFactors[Emulator.SystemId] < WINDOW_SCALE_MAX)
```

2024-03-19 22:34 UTC, YoshiRulz approved these changes

2024-03-19 22:34 UTC, YoshiRulz commented on src/BizHawk.Client.EmuHawk/MainForm.Events.cs
> +			Config.TargetZoomFactors[Emulator.SystemId] = (int) ((Control)sender).Tag;
I made a typo earlier, this needs to be:
```suggestion
			Config.TargetZoomFactors[Emulator.SystemId] = (int) ((ToolStripMenuItem) sender).Tag;
```
Other than that, this looks great, thanks for contributing!

2024-03-19 23:48 UTC, merged