Fix non-PSX disc hashing somewhat
TASEmulators/BizHawk pull request #4024
Opened 2024-09-08 10:05 UTC by kalimag

Fix `DiscHasher.OldHash()` method used to hash non-PSX discs
- Don't hash generated (empty) lead-in/lead-out tracks
- Limit to track length, not absolute LBA of next track

Previously, Saturn and Sega CD discs are all hashed to the same value `D41D8CD98F00B204E9800998ECF8427E` (empty sequence). This happens because the method is trying to hash the non-existent lead-in track and `track.NextTrack.LBA` is `0` (the LBA of the "real" first track).

Hashing PC Engine discs already mostly worked because the first track is an audio track and the lead-in track copies the mode of the first track and is skipped. A handful of discs where the first data track is <512 sectors may generate a different hash now, because the old implementation was reading past the end of the track. The only examples of that I could find were some unlicensed games that weren't in the gamedb.

Jaguar CD hashing still doesn't work because all tracks are marked as audio on those discs.

[//]: # "Apart from the mandatory license signature, these tasks are optional, but doing them could save reviewers some time and get the PR merged sooner."
Check if completed:
- [x] I have run any relevant test suites
- [x] I, the committer, have read the [licensing terms for contributors](https://github.com/TASEmulators/BizHawk/blob/master/contributing.md#copyrights-and-licensing) (last updated 2024-06-22) and am compliant

2024-09-08 10:13 UTC, YoshiRulz commented
Does this resolve #1075 then? That would be huge.

2024-09-08 10:22 UTC, kalimag commented
Kind of? I tested a fair number of Saturn, Sega CD and PC Engine discs, and didn't find any collisions between different games. However, different revisions/bad dumps do occasionally produce the same hash, which is expected since it's only hashing the first track.

BizHawk now has another set of console-specific disc hashing functions in the RA code. I don't know how well they deal with revisions, but perhaps reusing those for general hashing would also be an option. They currently live in the `EmuHawk` project, but other than swapping out the RA `ConsoleID` for BizHawks `DiscId` or `SystemId` it probably wouldn't be hard to move them into the disc or common project.

2024-09-08 21:32 UTC, CasualPokePlayer commented
> BizHawk now has another set of console-specific disc hashing functions in the RA code. I don't know how well they deal with revisions, but perhaps reusing those for general hashing would also be an option. They currently live in the EmuHawk project, but other than swapping out the RA ConsoleID for BizHawks DiscType or SystemId it probably wouldn't be hard to move them into the disc or common project.

FWIW, doing this could also help solve the issue of 3DS hashing, as rcheevos has their own limited hashing method for it. The downside of course, is it requires firmware (aes_keys.txt / seeddb.bin) in the case the game is encrypted (although if the firmware is not present the game couldn't be loaded anyways).

The disc hashing code too is also meant to be more a secondary implementation compared to the rcheevos implementation, although I've been mulling considering just removing it and deferring the hashing code entirely to rcheevos, like debug hashing code does (it has callbacks set in place so it will end up using our own disc system just fine). For general hashing however, it could perhaps still be better to have our own implementation so we are not directly subject to rcheevos in normal use (i.e. most users).

2024-09-08 21:55 UTC, CasualPokePlayer commented
> Does this resolve #1075 then? That would be huge.

Jaguar CD still won't work with this approach. Fundementally, Jaguar CDs are "audio" CDs, they never have "data tracks" (this was a design decision by Atari to squeeze out more space, at of course the obvious cost of no error correction data and so a much higher risk of disc read failures). You'd want a specialized disc hashing approach here, likely doing what [RA does](https://github.com/TASEmulators/BizHawk/blob/a72b0f7e8c181f3b140ab401238c4f77f08ad0f7/src/BizHawk.Client.EmuHawk/RetroAchievements/RetroAchievements.GameVerification.cs#L168-L275).

2024-09-08 22:02 UTC, CasualPokePlayer requested changes

2024-09-08 22:02 UTC, CasualPokePlayer commented on src/BizHawk.Emulation.DiscSystem/DiscHasher.cs
> +			for (int i = 1; i < disc.Session1.Tracks.Count - 1; i++)
Use `i <= disc.Session1.InformationTrackCount;` rather here.

2024-09-08 22:49 UTC, YoshiRulz commented on src/BizHawk.Emulation.DiscSystem/DiscHasher.cs
> +			for (int i = 1; i < disc.Session1.Tracks.Count - 1; i++)
```suggestion
			for (int i = 1; i <= disc.Session1.InformationTrackCount; i++)
```
?

2024-09-09 00:04 UTC, CasualPokePlayer approved these changes

2024-09-10 14:35 UTC, kalimag commented
- Is there any reason not to also hash the TOC for non-PSX discs? (apart from #3760)
- Should there be special handling for old movies saved with the meaningless `D41D8CD98F00B204E9800998ECF8427E` hash? 
- Is it alright to just duplicate the Jaguar CD hashing code from the RA integration into the DiscSystem project to cover that system as well?

2024-09-14 12:29 UTC, merged

2024-09-14 18:45 UTC, YoshiRulz commented
I'm afraid this didn't end up making it into RC1. I think it's because I pushed `master:release` without pulling `master`.