[C64] Fix memory performance issues
TASEmulators/BizHawk pull request #4152
Opened 2024-12-31 09:32 UTC by SaxxonPike

Addresses https://github.com/TASEmulators/BizHawk/issues/4151

Causes:

- Rewind functionality causes the full sync to be called every frame for C64 core - this was allocating large buffers to compare each bit on each track of each disk, which adds up (a whole disk bit-for-bit at the flux level is 16 megabytes)
- Synchronization for writeable media used on EasyFlash cartridges was affected by a similar issue

Solutions:

- Allocate re-usable buffers in the C64 core
- Add support for using these buffers in the Serializer class
- In places where arrays must be used, ArrayPool is sufficient to bridge the gap

Practical tests run:

- Unit tests
- Load and save state using C64 disk media (D64, PRG)
- Load and save state using C64 cartridge media (CRT)
- Load and save state on some other cores

Comments:

- In order to get access to Span APIs, the use of BaseStream in BinaryReader/BinaryWriter were necessary. We don't have anything that derives from these, but it's not exactly the most comfortable method (though it is the most direct and requires the least code.)

Check if completed:

- [x] I have run any relevant test suites
- [x] I, the committer, have read the [licensing terms for contributors](https://github.com/TASEmulators/BizHawk/blob/master/contributing.md#copyrights-and-licensing) (last updated 2024-06-22) and am compliant

2024-12-31 15:39 UTC, CasualPokePlayer submitted a review, later dismissed

2024-12-31 15:39 UTC, CasualPokePlayer commented on src/BizHawk.Common/DeltaSerializer.cs
> +			Marshal.SizeOf<T>() * count;
sizeof() should be used, not Marshal.SizeOf<> (which has different semantics and is much slower)

2024-12-31 16:04 UTC, YoshiRulz requested changes
What part of this is using `ArrayPool`? If you scrapped all of this and simply swapped out allocations for `ArrayPool`, how effective would that be?

2024-12-31 16:04 UTC, YoshiRulz commented on src/BizHawk.Emulation.Cores/Computers/Commodore64/Media/Disk.cs
> +			Parallel.ForEach(Partitioner.Create(0, _tracks.Length), range =>
Weird but okay

2025-01-01 16:58 UTC, SaxxonPike commented
Thanks for the feedback. Having stepped away and come back to it, I think the scope of these changes is larger than it needs to be. I'm going to put in refinements this week.

2025-01-04 08:30 UTC, YoshiRulz approved these changes
Rebase again and I think this is good. And please update the OP, including your estimate for the performance boost.

2025-01-04 18:51 UTC, SaxxonPike commented
Performance results added. The results are similar across all tested disks- I just used one as an example.

2025-01-04 19:13 UTC, YoshiRulz commented
Do you need help with rebasing? I was expecting
```
p 4f34320b3
p abf2014d3
p d6223e8ef
f ff92bddb5
p d9d629e1b
```

2025-01-06 09:38 UTC, YoshiRulz commented
Is [this](https://github.com/YoshiRulz/BizHawk_BranchBackup/commits/disk-delta-fixes-yoshi/) what you intended?

2025-01-06 18:21 UTC, SaxxonPike commented
Yeah, I think some of the branch history got a bit muddled. That looks fine to me. For posterity, the commit list should look more like this: https://github.com/SaxxonPike/BizHawk/tree/disk-delta-fixes-merge

2025-01-06 20:15 UTC, YoshiRulz commented
Would you like to force-push that here then?

2025-01-07 12:06 UTC, merged

2025-01-07 17:30 UTC, SaxxonPike commented
@YoshiRulz Thank you for taking care of this.